debug = true
console_address = "localhost:4200"
container_uid = 1000
container_gid = 1000
run_dir = "target/northstar/run"
data_dir = "target/northstar/data"

[repositories.default]
dir = "target/northstar/repository"
key = "examples/keys/northstar.pub"

[cgroups]
memory = "northstar"
cpu = "northstar"

[devices]
unshare_root = "/"
unshare_fstype = "ext4"
loop_control = "/dev/loop-control"
loop_dev = "/dev/loop"
device_mapper = "/dev/mapper/control"
device_mapper_dev = "/dev/dm-"

[bridge]
enabled = false
ipv4_slash16 = "172.30.0.0"
